### ISSUE TITLE
我有个需求，不知道能否实现

### ISSUE THREAD

**Issue by hegelsu** [idevzhou/ZYYRulerView#1]
就是我想实现这个时刻表中的某些段的背景色，比如时刻表总长为1点到23点，其中8点到12点为绿色，13点到18点为红色，不知道可否实现

**Comment by objbee** [comment]
这个不可以，如果长度固定（1-23），我认为完全可以自定义一个定长的画布来实现。如果觉得 layer 不好实现，也可以用 view 堆上去，性能也没有大的影响。
